### ISSUE TITLE
Won't work if the codespace doesn't have a SSH server

### ISSUE THREAD

**Issue by elfehr** [patrickt/codespaces.el#19]
Hello! I guess this is obvious in retrospect, but TRAMP won't be able to access the codespace if it doesn't support SSH.  I'd suggest adding in the readme to check that `gh codespace ssh` succeeds, to avoid raising false hopes :)

```
error getting ssh server details: failed to start SSH server: 
Please check if an SSH server is installed in the container.
If the docker image being used for the codespace does not have an SSH server,
install it in your Dockerfile or, for codespaces that use Debian-based images,
you can add the following to your devcontainer.json:

"features": {
    "ghcr.io/devcontainers/features/sshd:1": {
        "version": "latest"
    }
}
```

(This is a codespace for a class I'm taking, so I won't be able to install an SSH server.)

**Comment by patrickt** [comment]
Oh, interesting. I didn’t even know that was an option. How do you connect to the server if it lacks an ssh port open? The VSCode plugin?

**Comment by elfehr** [comment]
Yes, either online with a VSCode interface, or with desktop VSCode and the codespaces plugin.
